---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-runner
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: forgejo-runner-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        CONFIG_NAME: "{{ .CONFIG_NAME }}"
        CONFIG_INSTANCE: "{{ .CONFIG_INSTANCE }}"
        CONFIG_TOKEN: "{{ .CONFIG_TOKEN }}"
  dataFrom:
    - extract:
        key: forgejo-runner