---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
components:
  - ../../components/common
resources:
  - ./namespace.yaml
  - ./audiobookshelf/ks.yaml
  - ./bazarr/ks.yaml
  - ./huntarr/ks.yaml
  # - ./jellyseerr/ks.yaml
  - ./kometa/ks.yaml
  - ./music-assistant/ks.yaml
  - ./posterizarr/ks.yaml
  - ./prowlarr/ks.yaml
  - ./radarr/ks.yaml
  - ./readarr/ks.yaml
  - ./recyclarr/ks.yaml
  - ./sonarr/ks.yaml
  - ./tautulli/ks.yaml
  - ./watchstate/ks.yaml