---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app technitium-dns
spec:
  chartRef:
    kind: OCIRepository
    name: technitium-dns
  interval: 1h
  values:
    fullnameOverride: *app
    provider:
      name: rfc2136
    env:
      - name: &name TSIG_KEY
        valueFrom:
          secretKeyRef:
            name: &secret technitium-dns-secret
            key: *name
    extraArgs:
      - --rfc2136-host=10.1.10.2
      - --rfc2136-port=53
      - --rfc2136-zone=noms.tv
      - --rfc2136-tsig-secret-alg=hmac-sha256
      - --rfc2136-tsig-keyname=$(TSIG_KEY)
      - --rfc2136-tsig-axfr
    triggerLoopOnEvent: true
    policy: sync
    sources:
      - crd
      - gateway-httproute
    txtOwnerId: default
    txtPrefix: k8s.
    domainFilters:
      - noms.tv
    serviceMonitor:
      enabled: true
    podAnnotations:
      secret.reloader.stakater.com/reload: *secret