---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app technitium-dns
spec:
  chartRef:
    kind: OCIRepository
    name: technitium-dns
  interval: 1h
  values:
    fullnameOverride: *app
    env:
      - name: EXTERNAL_DNS_RFC2136_TSIG_SECRET
        valueFrom:
          secretKeyRef:
            name: technitium-dns-secret
            key: TSIG_KEY
    extraArgs:
      - --rfc2136-host=10.1.10.3
      - --rfc2136-port=53
      - --rfc2136-zone=noms.tv
      - --rfc2136-tsig-secret-alg=hmac-sha256
      - --rfc2136-tsig-keyname=external-dns
      - --rfc2136-tsig-axfr
    policy: sync
    provider:
      name: rfc2136
    sources:
      - gateway-httproute
    serviceMonitor:
      enabled: true
