---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: reitti
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: reitti-secret
    template:
      engineVersion: v2
      data:
        POSTGIS_USER: "{{ .appUser }}"
        POSTGIS_PASSWORD: "{{ .appPassword }}"
        RABBITMQ_USER: "{{ .rabbitmq_username }}"
        RABBITMQ_PASSWORD: "{{ .rabbitmq_password }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: reitti