apiVersion: v1
kind: ServiceAccount
metadata:
  name: rtlamr2mqtt-restart
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rtlamr2mqtt-restart
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rtlamr2mqtt-restart
subjects:
  - kind: ServiceAccount
    name: rtlamr2mqtt-restart
roleRef:
  kind: Role
  name: rtlamr2mqtt-restart
  apiGroup: rbac.authorization.k8s.io
