---
# yaml-language-server: $schema=https://crd.movishell.pl/postgresql.cnpg.io/database_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: reitti
  labels:
    app: reitti
spec:
  cluster:
    name: postgis
  extensions:
    - name: postgis
      ensure: present
  name: reitti
  owner: app