---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitea
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: gitea
    template:
      engineVersion: v2
      data:
        runner-token: "{{ .runnerToken | b64enc }}"
        app.ini: |
            APP_NAME = Noms's Gitea Server
            RUN_USER = git
            RUN_MODE = prod
            WORK_PATH = /var/lib/gitea

            [indexer]
            ISSUE_INDEXER_TYPE = db

            [repository]
            ROOT = /var/lib/gitea/git/repositories

            [repository.local]
            LOCAL_COPY_PATH = /tmp/gitea/local-repo

            [repository.upload]
            TEMP_PATH = /tmp/gitea/uploads

            [server]
            LFS_JWT_SECRET = {{ .lfsJwtSecret }}
            ROOT_URL = https://{{ .uiUrl }}
            ENABLE_PPROF = false
            SSH_PORT = 22
            APP_DATA_PATH = /var/lib/gitea
            SSH_LISTEN_PORT = 2222
            PROTOCOL = http
            HTTP_PORT = 3000
            START_SSH_SERVER = true
            SSH_DOMAIN = {{ .sshUrl }}
            DOMAIN = {{ .uiUrl }}

            [database]
            NAME = gitea
            DB_TYPE = postgres
            HOST = main-db-rw.databases:5432
            USER = {{ .appUser }}
            PASSWD = {{ .appPassword }}
            SCHEMA = public

            [session]
            PROVIDER_CONFIG = /var/lib/gitea/data/sessions

            [picture]
            AVATAR_UPLOAD_PATH = /var/lib/gitea/data/avatars
            REPOSITORY_AVATAR_UPLOAD_PATH = /var/lib/gitea/data/repo-avatars

            [attachment]
            PATH = /var/lib/gitea/data/attachments

            [log]
            ROOT_PATH = /var/lib/gitea/data/log

            [security]
            INTERNAL_TOKEN = {{ .internalToken }}
            SECRET_KEY =  {{ .secretKey }}
            INSTALL_LOCK = true

            [metrics]
            ENABLED = false

            [oauth2]
            JWT_SECRET = {{ .oauthJwtSecret }}

            [service]
            REQUIRE_SIGNIN_VIEW = false
            DISABLE_REGISTRATION = true
  dataFrom:
    - extract:
        key: gitea
    - extract:
        key: cloudnative-pg