---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app technitium-dns
spec:
  chartRef:
    kind: OCIRepository
    name: technitium-dns
  interval: 1h
  values:
    fullnameOverride: *app
    provider:
      name: webhook
      webhook:
        image:
          repository: ghcr.io/roosmaa/external-dns-technitium-webhook
          tag: main@sha256:7987b36f5ecd701d5c43d0aa4f40f5f5af7a6f52825b82b4b9ba3cdfa90a193e
        env:
          - name: LISTEN_PORT
            value: "8888"
          - name: RUST_LOG
            value: "external_dns_technitium_webhook=info"
          - name: TECHNITIUM_URL
            valueFrom:
              secretKeyRef:
                name: &secret technitium-dns-secret
                key: TECHNITIUM_URL
          - name: TECHNITIUM_USERNAME
            valueFrom:
              secretKeyRef:
                name: &secret technitium-dns-secret
                key: TECHNITIUM_USERNAME
          - name: TECHNITIUM_PASSWORD
            valueFrom:
              secretKeyRef:
                name: &secret technitium-dns-secret
                key: TECHNITIUM_PASSWORD
          - name: ZONE
            valueFrom:
              secretKeyRef:
                name: &secret technitium-dns-secret
                key: ZONE
        livenessProbe:
          httpGet:
            path: /health
            port: &port 8888
          initialDelaySeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: *port
          initialDelaySeconds: 10
          timeoutSeconds: 5
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
    triggerLoopOnEvent: true
    policy: sync
    sources:
      - service
      - gateway-httproute
    txtOwnerId: main
    txtPrefix: k8s.main
    domainFilters:
      - noms.tv
    serviceMonitor:
      enabled: true
    podAnnotations:
      secret.reloader.stakater.com/reload: *secret