---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app technitium-dns
spec:
  chartRef:
    kind: OCIRepository
    name: technitium-dns
  interval: 1h
  values:
    fullnameOverride: *app
    dnsConfig:
      nameservers:
        - 10.1.10.2
        - 10.1.10.3
        - 10.1.10.4
    env:
      - name: "EXTERNAL_DNS_RFC2136_TSIG_SECRET"
        valueFrom:
          secretKeyRef:
            name: &secret technitium-dns-secret
            key: TSIG_KEY
      - name: "EXTERNAL_DNS_RFC2136_TSIG_KEYNAME"
        valueFrom:
          secretKeyRef:
            name: *secret
            key: TSIG_KEY_NAME
    extraArgs:
      - --rfc2136-host=10.1.10.2
      - --rfc2136-port=53
      - --rfc2136-zone=noms.tv
      - --rfc2136-tsig-secret-alg=hmac-sha256
      - --rfc2136-tsig-axfr
    provider:
      name: rfc2136
    logLevel: debug
    triggerLoopOnEvent: true
    policy: sync
    sources:
      - gateway-httproute
    txtOwnerId: default
    txtPrefix: k8s.
    domainFilters:
      - noms.tv
    serviceMonitor:
      enabled: true
    podAnnotations:
      secret.reloader.stakater.com/reload: *secret
