---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: forgejo-home-ops-runner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: forgejo-home-ops-runner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: forgejo-home-ops-runner
    namespace: source-control
---
apiVersion: talos.dev/v1alpha1
kind: ServiceAccount
metadata:
  name: forgejo-home-ops-runner
spec:
  roles:
    - os:admin
