---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: main-cnpg-admin-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: main-cnpg-admin-secret
    template:
      engineVersion: v2
      type: kubernetes.io/basic-auth
      data:
        username: "{{ .postgresUser | toString }}"
        password: "{{ .postgresPassword | toString }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: main-cnpg-app-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: main-cnpg-app-secret
    template:
      engineVersion: v2
      type: kubernetes.io/basic-auth
      data:
        username: "{{ .appUser | toString }}"
        password: "{{ .appPassword | toString }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: main-cnpg-backup-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: main-cnpg-backup-secret
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        aws-access-key-id: "{{ .accessKeyId }}"
        aws-secret-access-key: "{{ .secretAccessKey }}"
        # garage-key-id: "{{ .KeyID }}"
        # garage-secret-key: "{{ .SecretKey }}"
  dataFrom:
    - extract:
        key: minio
    # - extract:
    #     key: garage