apiVersion: v1
kind: Service
metadata:
  name: main-db-external
  namespace: databases
  labels:
    app: main-db
  annotations:
    lbipam.cilium.io/ips: 10.1.20.28
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    cnpg.io/cluster: main-db
    role: primary