---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/probe_v1.json
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: icmp-iot
spec:
  module: icmp
  prober:
    url: blackbox-exporter-iot.observability.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - zwave-poe.iot.noms.tv
        - zigbee-poe.iot.noms.tv
  metricRelabelings:
    - targetLabel: service
      replacement: blackbox-exporter-iot
      action: replace