---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/probe_v1.json
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: icmp-internal
spec:
  module: icmp
  prober:
    url: blackbox-exporter-internal.observability.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - truenas.internal
  metricRelabelings:
    - targetLabel: service
      replacement: blackbox-exporter-internal
      action: replace
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/probe_v1.json
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: tcp-internal
spec:
  module: tcp_connect
  prober:
    url: blackbox-exporter-internal.observability.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - truenas.internal:2049
  metricRelabelings:
    - targetLabel: service
      replacement: blackbox-exporter-internal
      action: replace