---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app headlamp
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: *app
  values:
    config:
      clusterRoleBinding:
        clusterRoleName: headlamp
      oidc:
        externalSecret:
          enabled: true
          name: "headlamp-secret"
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
    persistentVolumeClaim:
      enabled: true
      accessModes: 
        - ReadWriteOnce
      size: 10Gi
      storageClassName: ceph-block
    # httpRoute: ## This will work after v0.40 is released. https://github.com/kubernetes-sigs/headlamp/pull/4299
    #   enabled: true
    #   parentRefs:
    #     - name: envoy-internal
    #       namespace: network
    #       sectionName: https
    #   hostnames:
    #     - "headlamp.noms.tv"