---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dispatcharr-celery
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: dispatcharr-celery-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DJANGO_SECRET_KEY: "{{ .SECRET_KEY }}"
        POSTGRES_USER: "{{ .appUser }}"
        POSTGRES_PASSWORD: "{{ .appPassword }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: arr-apps