---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: manyfold
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: manyfold-secret
    template:
      engineVersion: v2
      data:
        DATABASE_USER: "{{ .appUser }}"
        DATABASE_PASSWORD: "{{ .appPassword }}"
        SECRET_KEY_BASE: "{{ .secretKey }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: manyfold