---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app gitea-runner-apple
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      *app :
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: gitea/act_runner
              tag: 0.2.13@sha256:8477d5b61b655caad4449888bae39f1f34bebd27db56cb15a62dccb3dcf3a944
            command: ["sh", "-c", "while ! nc -z localhost 2376 </dev/null; do echo 'waiting for docker daemon...'; sleep 5; done; /sbin/tini -- run.sh"]
            env:
              DOCKER_HOST: tcp://localhost:2376
              DOCKER_CERT_PATH: /certs/client
              DOCKER_TLS_VERIFY: "1"
              GITEA_INSTANCE_URL: https://git.noms.tv
              GITEA_RUNNER_REGISTRATION_TOKEN:
                valueFrom:
                  secretKeyRef:
                    name: gitea
                    key: runner-token
            resources:
              limits:
                memory: 4G
          docker:
            image:
              repository: docker
              tag: 29.1.3-dind@sha256:173f284a4299164772a90f52b373e73e087583c0963f1334c9995f190ef6f3f5
            env:
              DOCKER_TLS_CERTDIR: /certs
            resources:
              limits:
                memory: 4G
            securityContext:
              privileged: true
    persistence:
      data:
        existingClaim: *app
        globalMounts:
          - path: /certs
            subPath: certs
          - path: /data
            subPath: data
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app gitea-runner-banana
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      *app :
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: gitea/act_runner
              tag: 0.2.13@sha256:8477d5b61b655caad4449888bae39f1f34bebd27db56cb15a62dccb3dcf3a944
            command: ["sh", "-c", "while ! nc -z localhost 2376 </dev/null; do echo 'waiting for docker daemon...'; sleep 5; done; /sbin/tini -- run.sh"]
            env:
              DOCKER_HOST: tcp://localhost:2376
              DOCKER_CERT_PATH: /certs/client
              DOCKER_TLS_VERIFY: "1"
              GITEA_INSTANCE_URL: https://git.noms.tv
              GITEA_RUNNER_REGISTRATION_TOKEN:
                valueFrom:
                  secretKeyRef:
                    name: gitea
                    key: runner-token
            resources:
              limits:
                memory: 4G
          docker:
            image:
              repository: docker
              tag: 29.1.3-dind@sha256:173f284a4299164772a90f52b373e73e087583c0963f1334c9995f190ef6f3f5
            env:
              DOCKER_TLS_CERTDIR: /certs
            resources:
              limits:
                memory: 4G
            securityContext:
              privileged: true
    persistence:
      data:
        existingClaim: *app
        globalMounts:
          - path: /certs
            subPath: certs
          - path: /data
            subPath: data
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app gitea-runner-cantaloupe
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      *app :
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: gitea/act_runner
              tag: 0.2.13@sha256:8477d5b61b655caad4449888bae39f1f34bebd27db56cb15a62dccb3dcf3a944
            command: ["sh", "-c", "while ! nc -z localhost 2376 </dev/null; do echo 'waiting for docker daemon...'; sleep 5; done; /sbin/tini -- run.sh"]
            env:
              DOCKER_HOST: tcp://localhost:2376
              DOCKER_CERT_PATH: /certs/client
              DOCKER_TLS_VERIFY: "1"
              GITEA_INSTANCE_URL: https://git.noms.tv
              GITEA_RUNNER_REGISTRATION_TOKEN:
                valueFrom:
                  secretKeyRef:
                    name: gitea
                    key: runner-token
            resources:
              limits:
                memory: 4G
          docker:
            image:
              repository: docker
              tag: 29.1.3-dind@sha256:173f284a4299164772a90f52b373e73e087583c0963f1334c9995f190ef6f3f5
            env:
              DOCKER_TLS_CERTDIR: /certs
            resources:
              limits:
                memory: 4G
            securityContext:
              privileged: true
    persistence:
      data:
        existingClaim: *app
        globalMounts:
          - path: /certs
            subPath: certs
          - path: /data
            subPath: data