---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: internal
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "internal",
      "plugins": [
        {
          "type": "macvlan",
          "master": "end0.10",
          "mode": "bridge",
          "ipam": {
            "type": "static",
            "routes": [
              { "dst": "0.0.0.0/0", "gw": "10.1.10.1" }
            ]
          }
        },
        {
          "type": "sbr"
        }
      ]
    }