---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: unpackerr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: unpackerr-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        UN_SONARR_0_URL: http://sonarr.media.svc.cluster.local
        UN_SONARR_0_API_KEY: "{{ .SonarrAPIKey }}"
        UN_SONARR_0_PATHS: "/media/Downloads/Complete"
        UN_SONARR_0_PROTOCOLS: torrent,usenet
        UN_RADARR_0_URL: http://radarr.media.svc.cluster.local
        UN_RADARR_0_API_KEY: "{{ .RadarrAPIKey }}"
        UN_RADARR_0_PATHS: "/media/Downloads/Complete"
        UN_RADARR_0_PROTOCOLS: torrent,usenet
        UN_READARR_0_URL: http://readarr.media.svc.cluster.local:8787
        UN_READARR_0_API_KEY: "{{ .ReadarrAPIKey }}"
        UN_READARR_0_PATHS: "/media/Downloads/Complete"
        UN_READARR_0_PROTOCOLS: torrent,usenet
  dataFrom:
    - extract:
        key: arr-apps