---
apiVersion: v1
kind: Namespace
metadata:
  name: actions-runner-system
  labels:
    pod-security.kubernetes.io/enforce: privileged ##TODO: Idk if this is needed
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
  annotations:
    kustomize.toolkit.fluxcd.io/prune: enabled
    volsync.backube/privileged-movers: "true"