---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forgejo-runner
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: forgejo-runner
  values:
    replicaCount: 1
    runner:
      config:
        existingInitSecret: "forgejo-runner-secret"
      file:
        runner:
          labels: ["home-ops-runner"]