apiVersion: postgresql.cnpg.io/v1
kind: ImageCatalog
metadata:
  name: timescaledb
spec:
  images:
    - major: 17
      # renovate: datasource=docker depName=timescale/timescaledb-ha
      image: timescale/timescaledb-ha:pg17.7-ts2.25.0@sha256:3c55ff3a00f8192f9076c41fe77024529b41f51dcbe59bbbaaf7106251d127c4