---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: syncstorage-rs-db
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: syncstorage-rs-db
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      syncstorage-rs-db:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: linuxserver/mariadb
              tag: 11.4.8@sha256:73a403f999eb7317b0fcd084f42bd77ed813f4e09d2a4ebc1ba90ea48e43041a
            env:
              MYSQL_USER: sync
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: &port 3306
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
    defaultPodOptions:
      securityContext:
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          sql:
            port: *port
    configMaps:
      init:
        data:
          init.sql: |-
            CREATE DATABASE IF NOT EXISTS syncstorage_rs;
            CREATE DATABASE IF NOT EXISTS tokenserver_rs;
            
            GRANT ALL PRIVILEGES
              ON syncstorage_rs.*
              TO sync;
            
            GRANT ALL PRIVILEGES
              ON tokenserver_rs.*
              TO sync;
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
      init:
        type: configMap
        identifier: init
        globalMounts:
          - path: /config/initdb.d/init.sql
            subPath: init.sql