---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: syncstorage-rs
spec:
  dependsOn:
    - name: syncstorage-rs-db
  interval: 30m
  path: ./kubernetes/apps/network/syncstorage-rs/app
  prune: true 
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: network
  timeout: 5m
  wait: false
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: syncstorage-rs-db
spec:
  components:
    - ../../../../components/volsync
  dependsOn:
    - name: volsync
      namespace: volsync-system
  interval: 30m
  path: ./kubernetes/apps/network/syncstorage-rs/db
  postBuild:
    substitute:
      APP: syncstorage-rs-db
      VOLSYNC_CAPACITY: 10Gi
  prune: true 
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: network
  timeout: 5m
  wait: false